site_name: MixerAPI
docs_dir: docs
plugins:
- simple:
    include_files:
    - .svg
- search
site_description: MixerAPI streamlines development of RESTful APIs for your CakePHP
  project
repo_url: https://github.com/mixerapi/mixerapi
edit_uri: ''
theme:
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: default
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - navigation.expand
nav:
- Baking Controllers: ./bake
- Exception Rendering: ./exception-render
- OpenAPI (Swagger): ./cakephp-swagger-bake
- Response Formats:
  - JSON / XML: ./collection-view
  - HAL+JSON: ./hal-view
  - JSON-LD: ./json-ld-view
- RESTful Routes: ./rest
markdown_extensions:
- pymdownx.highlight:
    extend_pygments_lang:
    - name: php
      lang: php
      options:
        startinline: true
    - name: pycon3
      lang: pycon
      options:
        python3: true
    linenums_style: pymdownx-inline
- pymdownx.superfences:
    preserve_tabs: true
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
    - name: math
      class: arithmatex
      format: !!python/name:pymdownx.arithmatex.fence_mathjax_format ''
