site_name: MixerAPI
docs_dir: docs
plugins:
- simple:
    include_files:
    - .svg
- search
site_description: MixerAPI streamlines development of RESTful APIs for your CakePHP
  project
repo_url: https://github.com/mixerapi/mixerapi
edit_uri: ''
theme:
  name: material
  palette:
    scheme: default
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - navigation.expand
  favicon: images/favicon.png
  logo: assets/logo.png
nav:
- Install: /install
- Getting Started: /workflow
- Baking Controllers: /bake
- Exception Rendering: /exception-render
- OpenAPI (Swagger):
  - Getting Started: /cakephp-swagger-bake
  - Annotations: /cakephp-swagger-bake/docs/annotations
  - Extensions: /cakephp-swagger-bake/docs/extensions
- Response Formats:
  - JSON / XML: /collection-view
  - HAL+JSON: /hal-view
  - JSON-LD: /json-ld-view
- RESTful Routes: /rest
- Search: /friends-of-cake-search
markdown_extensions:
- attr_list
- admonition
- pymdownx.details
- pymdownx.highlight:
    extend_pygments_lang:
    - name: php
      lang: php
      options:
        startinline: true
    - name: pycon3
      lang: pycon
      options:
        python3: true
    linenums_style: pymdownx-inline
- pymdownx.superfences:
    preserve_tabs: true
extra:
  social:
  - icon: fontawesome/brands/slack
    link: https://cakesf.slack.com/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/mixerapi
  - icon: fontawesome/brands/github
    link: https://github.com/mixerapi
