
name: deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy mixerapi.com
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/mixerapi.com
            ./deploy.sh
          host: mixerapi.com
          user: ${{ secrets.MIXERAPI_COM_USER}}
          key: ${{ secrets.MIXERAPI_COM_PUBLIC_KEY}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
